services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch_recommender
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # Optional
      - ingest.geoip.downloader.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 90s

volumes:
  elasticsearch_data:
